### ISSUE TITLE
Gnome3 中 UI 显示不正确

### ISSUE THREAD

**Issue by mengzhuo** [fanzeyi/kaname#5]
![2014-05-07 23 07 48](https://cloud.githubusercontent.com/assets/885662/2904206/8f451930-d5f9-11e3-8213-16022fcfd36a.png)

**Comment by mengzhuo** [comment]
而且还不能改变窗口的大小

**Comment by fanzeyi** [comment]
Chrome 设置中设置的缩放等级不为 100% 所致。

具体请 Follow Chromium 项目中 [Issue#153568](https://code.google.com/p/chromium/issues/detail?id=153568)
