### ISSUE TITLE
豆瓣授权后闪退

### ISSUE THREAD

**Issue by sen912** [fanzeyi/kaname#7]
每次打开后，输入豆瓣的用户名和密码后点击“授权”，然后就没任何界面了。
麻烦抽时间看下并更新啊，我是重度使用用户。

https://chrome.google.com/webstore/detail/%E8%B1%86%E7%93%A3%E7%94%B5%E5%8F%B0/pildlfoeifnhlckepgfiphlnaphcfhfh/support?utm_source=chrome-app-launcher

web store也有很多用户反应无法使用。

**Comment by fanzeyi** [comment]
Fixed.

Thanks for you feedback. =)

**Comment by sen912** [comment]
没看到代码更新啊？ 麻烦更新下Chrome web store
感谢~~

**Comment by fanzeyi** [comment]
并不需要。

**Comment by sen912** [comment]
已经可以正常登陆，非常非常感谢！

**Comment by fanzeyi** [comment]
@sen912 不客气。

**Comment by hizjz** [comment]
并没有修复，授权时还是闪退

**Comment by fanzeyi** [comment]
Chrome 要关掉所有的 packaged app 了，所以不修了…
